server:
  port: ${PORT:8761}

spring:
  application:
    name: ${APP_NAME:service-registry}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: ${EUREKA_FETCH:false}
