server:
  port: ${PORT:8090}

spring:
  application:
    name: ${SERVICE_NAME:auth-service}

eureka:
  client:
    service-url:
      defaultZone: https://${EUREKA_HOST:localhost}/eureka/
  instance:
    prefer-ip-address: true
    hostname: auth-service

# Feign is enabled via @EnableFeignClients in your main class
student:
  service:
    url: ${STUDENT_SERVICE_URL}